config/routes.rb
Rails.application.routes.draw do
  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end
  resources :maxims

end

app/models/maxim.rb
class Maxim < ActiveRecord::Base
  attr_accessor :uploading_file

  validate -> {upload_file_ext ['jpg', 'jpeg', 'png']}, if: :exists_file?
  validates :word,
            presence: true,
            length: {maximum: 150}
  validates :author,
            presence: true,
            length: {maximum: 50}
  validates :uploading_file,
            presence: true, on: :create

  before_create :create_image_file
  before_update :update_image_file, if: :exists_file?
  before_destroy :destroy_image_file

  def upload_file_ext white_list
    white_list.each do |ext|
      return true if File.extname(self.uploading_file.original_filename).downcase == ".#{ext}"
    end
    errors.add(:uploading_file, 'is invalid')
  rescue => e
    logger.error "Exception: #{e.message}"
    errors[:base] << "Validation failed"
    raise
  end

  def exists_file?
    !self.uploading_file.blank?
  end

  def create_image_file
    upload_file
  end

  def update_image_file
    delete_img_path = "#{get_upload_path}#{self.img_path}"
    upload_file
    File.delete(delete_img_path)
  rescue
    raise
  end

  def destroy_image_file
    delete_img_path = "#{get_upload_path}#{self.img_path}"
    File.delete(delete_img_path)
  rescue
    raise
  end

  def upload_file
    upload_path = get_upload_path
    mkdir_upload_path "#{UPLOAD_FILE_DIR}/#{IMAGES_DIR}"

    file_name = SecureRandom.uuid << File.extname(self.uploading_file.original_filename)
    full_path = upload_path << file_name

    File.open(full_path, 'wb') do |f|
      f.write self.uploading_file.read
    end

    self.img_path = file_name
  rescue => e
    logger.error "Exception: #{e.message}"
    raise
  end

  def get_upload_path
    "#{Rails.root.join("#{UPLOAD_FILE_DIR}/#{IMAGES_DIR}").to_s}/"
  end

  def mkdir_upload_path upload_path
    FileUtils.mkdir_p(upload_path) unless FileTest.exist?(upload_path)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/maxims_controller.rb
class MaximsController < ApplicationController
  before_action :set_maxim, only: [:show, :edit, :update, :destroy]

  # GET /maxims
  # GET /maxims.json
  def index
    @maxims = Maxim.page(params[:page])
  end

  # GET /maxims/1
  # GET /maxims/1.json
  def show
  end

  # GET /maxims/new
  def new
    @maxim = Maxim.new
  end

  # GET /maxims/1/edit
  def edit
  end

  # POST /maxims
  # POST /maxims.json
  def create
    @maxim = Maxim.new(maxim_params)

    respond_to do |format|
      if @maxim.save
        format.html { redirect_to @maxim, notice: 'Maxim was successfully created.' }
        format.json { render :show, status: :created, location: @maxim }
      else
        format.html { render :new }
        format.json { render json: @maxim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maxims/1
  # PATCH/PUT /maxims/1.json
  def update
    respond_to do |format|
      if @maxim.update(maxim_params)
        format.html { redirect_to @maxim, notice: 'Maxim was successfully updated.' }
        format.json { render :show, status: :ok, location: @maxim }
      else
        format.html { render :edit }
        format.json { render json: @maxim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maxims/1
  # DELETE /maxims/1.json
  def destroy
    @maxim.destroy
    respond_to do |format|
      format.html { redirect_to maxims_url, notice: 'Maxim was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maxim
      @maxim = Maxim.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def maxim_params
      params.require(:maxim).permit(:word, :author, :uploading_file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_img_path(img_name)
    "/#{IMAGES_DIR}/#{img_name}"
  end
end

app/helpers/maxims_helper.rb
module MaximsHelper
  def output_img(menu_img_name, option = {})
    image_tag get_img_path(menu_img_name), option
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Takeheart</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
</head>
<body>

<div class="container">
  <%= yield %>
</div>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
</body>
</html>

app/views/maxims/_form.html.erb
<%= form_for(@maxim) do |f| %>
  <% if @maxim.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@maxim.errors.count, "error") %> prohibited this maxim from being saved:</h2>

      <ul>
        <% @maxim.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :uploading_file %><br>
    <%= f.file_field :uploading_file %>
  </div>
  <div class="field">
    <div class="card z-depth-3">
      <div class="card-image h-img">
        <%= output_img @maxim.img_path, {style: 'width: 100%', class: 'display-img'} if @maxim.img_path.present? %>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maxims/edit.html.erb
<div class="row">
  <div class="col s12 m10 offset-m1 l10 offset-l1">
    <h1>Editing Maxim</h1>

    <%= render 'form' %>

    <%= link_to 'Destroy', @maxim, method: :delete, data: { confirm: 'Are you sure?' } %> |
    <%= link_to 'Show', @maxim %> |
    <%= link_to 'Back', maxims_path %>
  </div>
</div>

app/views/maxims/index.html.erb
<div class="row">
  <% @maxims.each do |maxim| %>
    <div class="col s12 m10 offset-m1 l10 offset-l1">
      <div class="card z-depth-3">
        <div class="card-image h-img">
          <%= link_to maxim_path(maxim) do %>
            <%= output_img maxim.img_path, {style: 'width: 100%', class: 'display-img'} %>
            <span class="card-title word">
              <%= maxim.word %>
              <span class="author">by <%= maxim.author %></span>
            </span>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="row">
  <div class="col s12 m10 offset-m1 l10 offset-l1">
    <%= paginate @maxims %>
  </div>
</div>
<div class="row">
  <div class="col s12 m10 offset-m1 l10 offset-l1">
    <%= link_to 'ADD', new_maxim_path, {class: 'waves-effect waves-light btn-large light-blue accent-4 z-depth-2'} %>
  </div>
</div>

app/views/maxims/new.html.erb
<div class="row">
  <div class="col s12 m10 offset-m1 l10 offset-l1">
    <h1>New Maxim</h1>

    <%= render 'form' %>

    <%= link_to 'Back', maxims_path %>
  </div>
</div>

app/views/maxims/show.html.erb
<div class="row">
  <div class="col s12 m10 offset-m1 l10 offset-l1">
    <p id="notice"><%= notice %></p>
    <div class="card z-depth-3">
      <div class="card-image h-img">
        <%= output_img @maxim.img_path, {style: 'width: 100%', class: 'display-img'} %>
        <span class="card-title word">
          <%= @maxim.word %>
          <span class="author">by <%= @maxim.author %></span>
        </span>
      </div>
    </div>

    <%= link_to 'Edit', edit_maxim_path(@maxim) %> |
    <%= link_to 'Back', maxims_path %>
  </div>
</div>